### PR TITLE
my new branch - first pull request

### PR DESCRIPTION
**Pull request by HelloIamAndre**
hey, I am trying to figure out how pull requests work. So this is my first pull request!

### CODE REVIEW

**Comment by HiImAndre** [comment]
Maybe you can write a little more in your txt file?

**Comment by HelloIamAndre** [comment]
> Maybe you can write a little more in your txt file?

okay will do it just right now!

**Comment by HelloIamAndre** [comment]
okay I added another line, what do you think about it now?

**Comment by HiImAndre** [comment]
it's perfect now. Let me see if I can merge it !

**Pull request merged**
